Update CI workflow and remove old binary

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -11,9 +11,9 @@ jobs:
       uses: actions/checkout@v3
 
     - name: Make binary executable
-      run: chmod +x ./bin/passgen_v.1.1
+      run: chmod +x ./bin/passgen
 
     - name: Run tests on binary
       run: |
-        ./bin/passgen_v.1.1 -n 12 -l -d -s
-        ./bin/passgen_v.1.1 -n 4 || echo "[OK] Detected invalid input"
+        ./bin/passgen -n 12 -l -d -s
+        ./bin/passgen -n 4 || echo "[OK] Detected invalid input"
